name: Merge
on:
  pull_request:
  merge_group:
jobs:
  merge_build:
    if: ${{ github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build
    - name: Update txt
      shell: bash
      run: |
        RANDOM_NUMBER=$((RANDOM % 1000000))
        echo "Hello World  $RANDOM_NUMBER" > hello.txt
        git add hello.txt
        git commit -m "Update hello.txt"
        git push
